export const products = [
  { id: 1, name: 'Men Shirt 1', category: 'men', subcategory: 'shirts' },
  { id: 2, name: 'Men Shirt 2', category: 'men', subcategory: 'shirts' },
  { id: 3, name: 'Men Jacket 1', category: 'men', subcategory: 'jackets' },
  { id: 4, name: 'Men Pants 1', category: 'men', subcategory: 'pants' },
  { id: 5, name: 'Men T-Shirt 1', category: 'men', subcategory: 't-shirts' },
  { id: 6, name: 'Men T-Shirt 2', category: 'men', subcategory: 't-shirts' },
  { id: 7, name: 'Men Hat 1', category: 'men', subcategory: 'accessories' },
  { id: 8, name: 'Men Hat 2', category: 'men', subcategory: 'accessories' },
  { id: 9, name: 'Men Socks 1', category: 'men', subcategory: 'accessories' },
  { id: 10, name: 'Men Shoes 1', category: 'men', subcategory: 'shoes' },
  { id: 11, name: 'Women Dress 1', category: 'women', subcategory: 'dresses' },
  { id: 12, name: 'Women Dress 2', category: 'women', subcategory: 'dresses' },
  { id: 13, name: 'Women Top 1', category: 'women', subcategory: 'tops' },
  { id: 14, name: 'Women Top 2', category: 'women', subcategory: 'tops' },
  { id: 15, name: 'Women Skirt 1', category: 'women', subcategory: 'skirts' },
  { id: 16, name: 'Women Bag 1', category: 'women', subcategory: 'accessories' },
  { id: 17, name: 'Women Heels 1', category: 'women', subcategory: 'shoes' },
  { id: 18, name: 'Women Heels 2', category: 'women', subcategory: 'shoes' },
  { id: 19, name: 'Women Sandals 1', category: 'women', subcategory: 'shoes' },
  { id: 20, name: 'Women Bag 2', category: 'women', subcategory: 'accessories' },
  { id: 21, name: 'Kid Toy 1', category: 'kid', subcategory: 'toys' },
  { id: 22, name: 'Kid Toy 2', category: 'kid', subcategory: 'toys' },
  { id: 23, name: 'Kid Book 1', category: 'kid', subcategory: 'books' },
  { id: 24, name: 'Kid Book 2', category: 'kid', subcategory: 'books' },
  { id: 25, name: 'Kid Shoes 1', category: 'kid', subcategory: 'shoes' },
  { id: 26, name: 'Kid Hat 1', category: 'kid', subcategory: 'accessories' },
  { id: 27, name: 'Kid Socks 1', category: 'kid', subcategory: 'accessories' },
  { id: 28, name: 'Kid Gloves 1', category: 'kid', subcategory: 'accessories' },
  { id: 29, name: 'Kid Jacket 1', category: 'kid', subcategory: 'jackets' },
  { id: 30, name: 'Kid Shirt 1', category: 'kid', subcategory: 'shirts' },
  { id: 31, name: 'Laptop', category: 'electronics', subcategory: 'computers' },
  { id: 32, name: 'Smartphone', category: 'electronics', subcategory: 'mobiles' },
  { id: 33, name: 'Tablet', category: 'electronics', subcategory: 'mobiles' },
  { id: 34, name: 'Headphones', category: 'electronics', subcategory: 'audio' },
  { id: 35, name: 'Smartwatch', category: 'electronics', subcategory: 'wearables' },
  { id: 36, name: 'Camera', category: 'electronics', subcategory: 'cameras' },
  { id: 37, name: 'Monitor', category: 'electronics', subcategory: 'computers' },
  { id: 38, name: 'Keyboard', category: 'electronics', subcategory: 'accessories' },
  { id: 39, name: 'Mouse', category: 'electronics', subcategory: 'accessories' },
  { id: 40, name: 'Charger', category: 'electronics', subcategory: 'accessories' },
  { id: 41, name: 'Sofa', category: 'home', subcategory: 'furniture' },
  { id: 42, name: 'Dining Table', category: 'home', subcategory: 'furniture' },
  { id: 43, name: 'Chair', category: 'home', subcategory: 'furniture' },
  { id: 44, name: 'Bed', category: 'home', subcategory: 'furniture' },
  { id: 45, name: 'Lamp', category: 'home', subcategory: 'decor' },
  { id: 46, name: 'Curtains', category: 'home', subcategory: 'decor' },
  { id: 47, name: 'Mirror', category: 'home', subcategory: 'decor' },
  { id: 48, name: 'Bookshelf', category: 'home', subcategory: 'furniture' },
  { id: 49, name: 'Carpet', category: 'home', subcategory: 'decor' },
  { id: 50, name: 'Vase', category: 'home', subcategory: 'decor' },
  { id: 51, name: 'Football', category: 'sports', subcategory: 'equipment' },
  { id: 52, name: 'Basketball', category: 'sports', subcategory: 'equipment' },
  { id: 53, name: 'Tennis Racket', category: 'sports', subcategory: 'equipment' },
  { id: 54, name: 'Badminton Racket', category: 'sports', subcategory: 'equipment' },
  { id: 55, name: 'Cricket Bat', category: 'sports', subcategory: 'equipment' },
  { id: 56, name: 'Football Shoes', category: 'sports', subcategory: 'shoes' },
  { id: 57, name: 'Golf Clubs', category: 'sports', subcategory: 'equipment' },
  { id: 58, name: 'Yoga Mat', category: 'sports', subcategory: 'accessories' },
  { id: 59, name: 'Swimming Goggles', category: 'sports', subcategory: 'accessories' },
  { id: 60, name: 'Dumbbells', category: 'sports', subcategory: 'equipment' },
  { id: 61, name: 'Kid Bag 1', category: 'kid', subcategory: 'accessories' },
  { id: 62, name: 'Men Sandals 1', category: 'men', subcategory: 'shoes' },
  { id: 63, name: 'Women Necklace 1', category: 'women', subcategory: 'jewelry' },
  { id: 64, name: 'Tablet 2', category: 'electronics', subcategory: 'mobiles' },
  { id: 65, name: 'Chair 2', category: 'home', subcategory: 'furniture' },
  { id: 66, name: 'Basketball Shoes', category: 'sports', subcategory: 'shoes' },
  { id: 67, name: 'Women Earrings', category: 'women', subcategory: 'jewelry' },
  { id: 68, name: 'Football 2', category: 'sports', subcategory: 'equipment' },
  { id: 69, name: 'Men Gloves 1', category: 'men', subcategory: 'accessories' },
  { id: 70, name: 'Kid Shoes 2', category: 'kid', subcategory: 'shoes' },
  { id: 71, name: 'Men Jacket 2', category: 'men', subcategory: 'jackets' },
  { id: 72, name: 'Women Dress 3', category: 'women', subcategory: 'dresses' },
  { id: 73, name: 'Home Vase 2', category: 'home', subcategory: 'decor' },
  { id: 74, name: 'Sports Headband', category: 'sports', subcategory: 'accessories' },
  { id: 75, name: 'Camera Lens', category: 'electronics', subcategory: 'cameras' },
  { id: 76, name: 'Kid Book 3', category: 'kid', subcategory: 'books' },
  { id: 77, name: 'Women Bag 3', category: 'women', subcategory: 'accessories' },
  { id: 78, name: 'Men T-Shirt 3', category: 'men', subcategory: 't-shirts' },
  { id: 79, name: 'Tablet Cover', category: 'electronics', subcategory: 'accessories' },
  { id: 80, name: 'Curtains 2', category: 'home', subcategory: 'decor' },
  { id: 81, name: 'Dumbbells 2', category: 'sports', subcategory: 'equipment' },
  { id: 82, name: 'Bed Sheets', category: 'home', subcategory: 'decor' },
  { id: 83, name: 'Golf Ball', category: 'sports', subcategory: 'equipment' },
  { id: 84, name: 'Monitor 2', category: 'electronics', subcategory: 'computers' },
  { id: 85, name: 'Dining Set', category: 'home', subcategory: 'furniture' },
  { id: 86, name: 'Yoga Block', category: 'sports', subcategory: 'accessories' },
  { id: 87, name: 'Kid Toy 3', category: 'kid', subcategory: 'toys' },
  { id: 88, name: 'Men Shirt 3', category: 'men', subcategory: 'shirts' },
  { id: 89, name: 'Laptop Bag', category: 'electronics', subcategory: 'accessories' },
  { id: 90, name: 'Women Top 3', category: 'women', subcategory: 'tops' },
  { id: 91, name: 'Camera Tripod', category: 'electronics', subcategory: 'cameras' },
  { id: 92, name: 'Bookshelf 2', category: 'home', subcategory: 'furniture' },
  { id: 93, name: 'Rug', category: 'home', subcategory: 'decor' },
  { id: 94, name: 'Football Kit', category: 'sports', subcategory: 'equipment' },
  { id: 95, name: 'Men Belt 1', category: 'men', subcategory: 'accessories' },
  { id: 96, name: 'Women Watch 1', category: 'women', subcategory: 'jewelry' },
  { id: 97, name: 'Men Wallet', category: 'men', subcategory: 'accessories' },
  { id: 98, name: 'Women Scarf', category: 'women', subcategory: 'accessories' },
  { id: 99, name: 'Kid Puzzle', category: 'kid', subcategory: 'toys' },
  { id: 100, name: 'Smartphone Case', category: 'electronics', subcategory: 'accessories' }
];

export const categories = [
  {
    category: 'men',
    subcategories: ['shirts', 'jackets', 'pants', 't-shirts', 'accessories', 'shoes']
  },
  {
    category: 'women',
    subcategories: ['dresses', 'tops', 'skirts', 'accessories', 'shoes', 'jewelry']
  },
  {
    category: 'kid',
    subcategories: ['toys', 'books', 'shoes', 'accessories', 'jackets', 'shirts']
  },
  {
    category: 'electronics',
    subcategories: ['computers', 'mobiles', 'audio', 'wearables', 'cameras', 'accessories']
  },
  {
    category: 'home',
    subcategories: ['furniture', 'decor']
  },
  {
    category: 'sports',
    subcategories: ['equipment', 'shoes', 'accessories']
  }
];
